# Generated by Django 3.0.9 on 2020-08-11 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faturamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(choices=[('SP', 'São Paulo'), ('MG', 'Minas Gerais'), ('NE', 'Nordeste'), ('PR', 'Paraná'), ('SC', 'Santa Catarina')], default='SP', max_length=2, verbose_name='Região')),
                ('city', models.CharField(choices=[(None, '------------------ CIDADES--------------------'), (None, '------------------São Paulo--------------------'), ('ABC', 'ABC'), ('Araçatuba', 'Araçatuba'), ('Bauru', 'Bauru'), ('Cumbica', 'Cumbica'), ('Praia Grande', 'Praia Grande'), ('Presidente Prudente', 'Presidente Prudente'), ('Ribeirão Preto', 'Ribeirão Preto'), ('Santa Barbara', 'Santa Barbara'), ('São José do Rio Preto', 'São José do Rio Preto'), ('Sorocaba', 'Sorocaba'), ('Taubaté', 'Taubaté'), ('Valinhos', 'Valinhos'), (None, '------------------Minas Gerais--------------------'), ('Contagem', 'Contagem'), ('Juiz de Fora', 'Juiz de Fora'), ('Montes Claros', 'Montes Claros'), ('Passos', 'Passos'), ('Sapucaí', 'Sapucaí'), ('Uberlândia', 'Uberlândia'), ('Vale do aço', 'Vale do aço'), (None, '------------------Sul--------------------'), ('Campo Mourão', 'Campo Mourão'), ('Cascavel', 'Cascavel'), ('Curitiba', 'Curitiba'), ('Francisco Beltrão', 'Francisco Beltrão'), ('Gaspar', 'Gaspar'), ('Guarapuava', 'Guarapuava'), ('Londrina', 'Londrina'), ('Maringá', 'Maringá'), ('Ponta Grossa', 'Ponta Grossa'), (None, '------------------Nordeste--------------------'), ('Maceió', 'Maceió'), ('Recife', 'Recife')], max_length=50, verbose_name='Cidade')),
                ('month', models.CharField(choices=[('1', 'Janeiro'), ('2', 'Fevereiro'), ('3', 'Março'), ('4', 'Abril'), ('5', 'Maio'), ('6', 'Junho'), ('7', 'Julho'), ('8', 'Agosto'), ('9', 'Setembro'), ('10', 'Outubro'), ('11', 'Novembro'), ('12', 'Dezembro')], default=8, max_length=2, verbose_name='Mês')),
                ('value', models.FloatField(verbose_name='Valor')),
            ],
        ),
    ]
